# Generated by Django 4.2.29 on 2026-08-06 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_ticket_qr_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingMPPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_id', models.CharField(db_index=True, max_length=400, unique=True)),
                ('mp_payment_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('external_reference', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('resulting_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mp_payment_record', to='tickets.ticket')),
                ('ticket_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.tickettype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago Pendiente MP',
                'verbose_name_plural': 'Pagos Pendientes MP',
                'ordering': ['-created_at'],
            },
        ),
    ]
