# Generated by Django 4.2.29 on 2026-08-07 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_ticket_qr_code'),
        ('payments', '0002_pendingmppayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingmppayment',
            name='resulting_ticket',
        ),
        migrations.RemoveField(
            model_name='pendingmppayment',
            name='ticket_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='ticket',
        ),
        migrations.AddField(
            model_name='pendingmppayment',
            name='cart_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ticket_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.tickettype')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='payments.transaction')),
            ],
        ),
    ]
