# Generated by Django 4.2.29 on 2026-03-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='web3_provider_url',
            field=models.URLField(default='http://127.0.0.1:8545', help_text='URL del nodo Web3 (Ej: Infura, Alchemy o local Ganache/Hardhat).'),
        ),
    ]
