# Generated by Django 4.2.29 on 2026-08-07 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_pendingmppayment_resulting_ticket_and_more'),
        ('tickets', '0002_remove_ticket_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='payments.transaction'),
        ),
    ]
